### ISSUE TITLE
Folium Tiles Water Color / Deprecated 

### ISSUE THREAD

**Issue by RobbeW** [deepmind/ithaca#6]
Hi all 

I noticed that the Folium team has removed the Stamen Water Color map from their tiles. This results in an unwanted result within the geographical reference indication (tl;dr: the map is just blank grey drab). 

[The discussion about the removal by the Folium team can be found here.](https://github.com/python-visualization/folium/pull/1811)

**Suggested quick-fix:** 

`folium.Map (tiles="openstreetmap")`

(I prefer the old water color style, so I will try to look more closely to the changelogs of the Folium and XYZ teams, but short term this will do the trick).

**Comment by iassael** [comment]
Hi Robbe, thank you so much for bringing this to our attention. We will soon try to submit a fix.

**Comment by iassael** [comment]
The issue has been fixed. Thank you @RobbeW !
